import { afterEach, beforeEach, describe, expect, it, mock, spyOn } from 'bun:test';
import { CodexAgentProvider } from './index.js';
import { CodexHeadlessProvider } from './headless.js';
import { CodexEventMapper } from './event-mapper.js';
import { serverManager, type CodexClient, type CodexModelList } from './server-manager.js';

// Fixtures follow the protocol generated by codex-cli 0.154.0. Exercise the
// actual providers so protocol drift cannot hide behind copied implementations.
describe('Codex app-server compatibility', () => {
  const threadId = '019e1277-6206-74e1-bb66-bbd8e9534628';
  let notify: (method: string, params: unknown) => void;
  let client: CodexClient;
  let acquire: ReturnType<typeof spyOn>;
  let release: ReturnType<typeof spyOn>;

  beforeEach(() => {
    client = {
      model: { list: mock(async (): Promise<CodexModelList> => ({ data: [], nextCursor: null })) },
      thread: {
        start: mock(async () => ({ thread: { id: threadId } })),
        resume: mock(async () => ({ thread: { id: threadId } })),
        read: mock(async () => ({ thread: { id: threadId } })),
      },
      turn: {
        start: mock(async () => ({ turn: { id: 'turn-1', status: 'inProgress' } })),
        interrupt: mock(async () => {}),
      },
      onNotification: handler => { notify = handler; return () => {}; },
      respondToServer: () => {},
      close: () => {},
    };
    acquire = spyOn(serverManager, 'acquire').mockResolvedValue(client);
    release = spyOn(serverManager, 'release').mockImplementation(() => {});
  });

  afterEach(() => { acquire.mockRestore(); release.mockRestore(); });

  it('uses wire IDs, display names, pagination and the server-selected default', async () => {
    client.model.list = mock(async ({ cursor } = {}) => cursor
      ? { data: [{ id: 'picker-b', model: 'model-b', displayName: 'Model B', isDefault: true }], nextCursor: null }
      : { data: [{ id: 'picker-a', model: 'model-a', displayName: 'Model A', isDefault: false }], nextCursor: 'page-2' });
    const models = await new CodexAgentProvider().listModels();
    expect(models.map(m => [m.id, m.displayName, m.isDefault])).toEqual([
      ['model-a', 'Model A', undefined], ['model-b', 'Model B', true],
    ]);
    expect(client.model.list).toHaveBeenCalledWith({ limit: 50, cursor: 'page-2' });
    expect(release).toHaveBeenCalledTimes(1);
  });

  it('still supports legacy model responses', async () => {
    client.model.list = mock(async () => ({ models: [{ id: 'legacy', name: 'Legacy' }] }));
    expect(await new CodexAgentProvider().listModels()).toEqual([
      { id: 'legacy', displayName: 'Legacy', description: undefined, isDefault: true },
    ]);
  });

  it('releases the server if model discovery fails', async () => {
    client.model.list = mock(async () => { throw new Error('catalog unavailable'); });
    await expect(new CodexAgentProvider().listModels()).rejects.toThrow('catalog unavailable');
    expect(release).toHaveBeenCalledTimes(1);
  });

  it('cancels with the turn ID even when stopped before turn/start responds', async () => {
    let resolveStart!: (value: { turn: { id: string } }) => void;
    client.turn.start = mock(() => new Promise(resolve => { resolveStart = resolve; }));
    const session = await new CodexHeadlessProvider().spawn({ workingDirectory: '/workspace', initialPrompt: 'test' });
    const interrupted = session.interrupt();
    expect(client.turn.interrupt).not.toHaveBeenCalled();
    resolveStart({ turn: { id: 'turn-pending' } });
    await interrupted;
    expect(client.turn.interrupt).toHaveBeenCalledWith({ threadId, turnId: 'turn-pending' });
    session.close();
    await Bun.sleep(0);
  });

  it('keeps the server until close cancellation is acknowledged', async () => {
    let finishInterrupt!: () => void;
    client.turn.interrupt = mock(() => new Promise<void>(resolve => { finishInterrupt = resolve; }));
    const session = await new CodexHeadlessProvider().spawn({ workingDirectory: '/workspace' });
    session.close();
    session.close();
    await Bun.sleep(0);
    expect(release).not.toHaveBeenCalled();
    finishInterrupt();
    await Bun.sleep(0);
    expect(release).toHaveBeenCalledTimes(1);
  });

  it('does not cancel completed turns or turns belonging to another thread', async () => {
    const session = await new CodexHeadlessProvider().spawn({ workingDirectory: '/workspace' });
    notify('turn/completed', { threadId, turn: { id: 'turn-1', status: 'completed' } });
    notify('turn/started', { threadId: 'other', turn: { id: 'other-turn' } });
    await session.interrupt();
    expect(client.turn.interrupt).not.toHaveBeenCalled();
    session.close();
    await Bun.sleep(0);
  });

  it('resumes the requested thread and forwards the selected model and prompt', async () => {
    const session = await new CodexHeadlessProvider().spawn({
      workingDirectory: '/workspace', resumeSessionId: threadId, model: 'selected-model', initialPrompt: 'continue',
    });
    expect(client.thread.resume).toHaveBeenCalledWith({
      threadId, model: 'selected-model', cwd: '/workspace', approvalPolicy: 'never', sandbox: 'danger-full-access',
    });
    expect(client.turn.start).toHaveBeenCalledWith({ threadId, input: [{ type: 'text', text: 'continue' }] });
    session.close();
    await Bun.sleep(0);
  });

  it('reports nested turn failures and interruptions instead of success', () => {
    const mapper = new CodexEventMapper();
    expect(mapper.mapNotification({ method: 'turn/completed', params: {
      threadId, turn: { id: 'turn-1', status: 'failed', error: { message: 'rate limit' } },
    } }, threadId)).toMatchObject([{ type: 'error', content: 'rate limit' }]);
    expect(mapper.mapNotification({ method: 'turn/completed', params: {
      threadId, turn: { id: 'turn-2', status: 'interrupted', error: null },
    } }, threadId)).toMatchObject([{ type: 'result', subtype: 'interrupted' }]);
  });

  it('distinguishes retry notifications from terminal errors', () => {
    const mapper = new CodexEventMapper();
    const params = { threadId, error: { message: 'connection lost' }, willRetry: true };
    expect(mapper.mapNotification({ method: 'error', params }, threadId)).toEqual([]);
    expect(mapper.mapNotification({ method: 'error', params: { ...params, willRetry: false } }, threadId))
      .toMatchObject([{ type: 'error', content: 'connection lost' }]);
  });

  it('uses complete command output when only part of it was streamed', () => {
    const mapper = new CodexEventMapper();
    mapper.mapNotification({ method: 'item/commandExecution/outputDelta', params: {
      threadId, itemId: 'cmd-1', delta: 'partial',
    } }, threadId);
    const messages = mapper.mapNotification({ method: 'item/completed', params: {
      threadId, item: { type: 'commandExecution', id: 'cmd-1', aggregatedOutput: 'complete output', exitCode: 0 },
    } }, threadId);
    expect(messages.find(message => message.type === 'tool_result')?.content).toBe('complete output');
  });
});
